### ISSUE TITLE
TeXworks unable to find Germania One font

### ISSUE THREAD

**Issue by pegs001** [nrnrnr/Frosthaven-YASS#1]
Hi,

I downloaded and, I assumed, installed the font at least to my PC. I am able to use the font in Word. Is there somewhere I need to point TeXworks too so it can find the font?

**Comment by pegs001** [comment]
I got around this by changing the fonts, now i have a new issue, will open ticket for that.

**Comment by argiron** [comment]
https://tex.stackexchange.com/questions/317102/xelatex-cant-find-font
