### ISSUE TITLE
TeXworks unable to load picture or PDF File error

### ISSUE THREAD

**Issue by pegs001** [nrnrnr/Frosthaven-YASS#2]
Hello,

I got the following error
`
`
LaTeX Warning: File `{Desktop/New folder/Frosthaven-YASS-main/assets/Frosthaven
/images/monster-stat-cards/frosthaven/}/fh-chaos-demon-0.png' not found on inpu
t line 205.

! Unable to load picture or PDF file '"{Desktop/New folder/Frosthaven-YASS-main
/assets/Frosthaven/images/monster-stat-cards/frosthaven/}/fh-chaos-demon-0.png"
'.
<to be read again> 
                   }
l.205 \monster*(1,5.5)[chaos-demon]{Chaos Demon}
                                                ;
? 
`

And the directory I have setup is

`
\newcommand\fhpath{{Desktop/New folder/Frosthaven-YASS-main/assets/Frosthaven/images/monster-stat-cards/frosthaven/}}
`

Attached will also be a picture. I did try having the directory be the one in here, and also the one having the drive and user such as 
C:/Users/username/Desktop/New folder/Frosthaven-YASS-main/assets/Frosthaven/images/monster-stat-cards/frosthaven/

![test](https://user-images.githubusercontent.com/64235741/215616897-0634d61b-9218-4312-9f39-1f088d77c0f4.PNG)

**Comment by nrnrnr** [comment]
Your definition of `\fhpath` appears to have an extra set of curly braces.  Try removing them.
